### PR TITLE
Add Docker image

### PR DESCRIPTION
**Pull request by bachya**
This PR adds support for a Docker image of the library. It includes updates to the README.

Once we merge this in, we can start on automatically pushing Docker images to Docker Hub (and GitHub Container Registry if we find that necessary). @bropat, do you have a Docker Hub account already? Could you create a `bropat/eufy-security-ws` repo there and invite me to it as a collaborator?

### CODE REVIEW

**Review by bropat — APPROVED** [review]
Nothing to complain about

**Comment by bropat** [comment]
@bachya 

> Could you create a bropat/eufy-security-ws repo there and invite me to it as a collaborator?

Already done ;)

**Comment by bachya** [comment]
@bropat I don't see this Docker Hub repo in my list; just the ones I have access to:

CleanShot 2021-05-13 at 17 04 47

To confirm, you invited me?

**Comment by bropat** [comment]
@bachya 
Yes i have:

image

Did you change the namespace?

image

**Comment by bachya** [comment]
@bropat No, I don't see that in my list of namespaces, unfortunately. That said, it may not matter as long as I can push. Do you have a place (Discord, Slack, whatever) where we can debug together?

**Comment by bropat** [comment]
@bachya Of course:

Discord: bropat#4284
Google meet: patrick.broetto@gmail.com

**Comment by bropat** [comment]
@bachya 

Docker image created :)

**Comment by bachya** [comment]
@bropat Cool! Did you set up Docker Hub to automatically build images based on pushes to `master`, tags, etc.?

**Comment by bropat** [comment]
@bachya Yes.

**Pull request merged**
